# Task Generator Configuration
# ============================
# This file configures the task generator

database:
  db_url: "sqlite:///C:/Users/USER/development/grepx-pricing-app/data/dagster_config_orm.db"

# Path to file containing tasks and assets definitions
tasks_file: "resources/tasks.yaml"

