# Task Generator Configuration
# ============================
# This file configures the task generator

database:
  db_url: "sqlite:///../grepx-dagster-server/dagster_config_orm.db"

# Path to files containing tasks and assets definitions
tasks_files:
  - "resources/pricing_tasks.yaml"
  - "resources/test_tasks.yaml"


